#!/bin/bash

# Learn HAM (good mails)
RESULT=$(sa-learn --dbpath /var/lib/spamassassin/.spamassassin --ham ${FRX_MAIL_DIR}/*/*/*/cur/*)
LOG_TIME=$(date +"%Y-%m-%d %H:%M:%S")

echo "${LOG_TIME} - HAM: ${RESULT}" >> ${LOG_DIR}/spamassassin-learn.log

# Learn SPAM (bad mails)
RESULT=$(sa-learn --dbpath /var/lib/spamassassin/.spamassassin --spam ${FRX_MAIL_DIR}/*/*/*/.Spam/cur/*)
LOG_TIME=$(date +"%Y-%m-%d %H:%M:%S")

echo "${LOG_TIME} - SPAM: ${RESULT}" >> ${LOG_DIR}/spamassassin-learn.log
